project_id = "buqgskkfoqftrpxtxkkr"

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.create-patient]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false