// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buqgskkfoqftrpxtxkkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1cWdza2tmb3FmdHJweHR4a2tyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTI1ODAsImV4cCI6MjA2OTk4ODU4MH0.T2T6kyPDs_ATLF6Ky67C1UsgQI7ikwd4W9U6np6weT8";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});